In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray', arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
myarray

NameError: name 'myarray' is not defined

In [7]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')

In [9]:
arr1

array([0, 1, 2, 3, 4])

In [10]:
arr2 = arr

In [11]:
np.savez('zipArray.npz',x = arr1, y= arr2)

In [13]:
archive_array = np.load('zipArray.npz')

In [14]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.savetxt('myTextArray.txt',arr,delimiter=',')

In [22]:
arr = np.loadtxt('myTextArray.txt', delimiter=',')

In [23]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])