In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

A

array([ 0.64182079,  0.34523529,  1.20792517,  0.95928417,  0.75058787,
        0.44267594,  1.94125291,  2.15974819, -0.43287598,  0.74310244])

In [7]:
B = np.random.randn(10)

In [8]:
B

array([ 1.64689696,  0.01812837,  0.83380196, -1.02083773,  0.00415207,
        1.49821232, -1.24574639, -0.77577586, -1.1657684 ,  0.39746308])

In [9]:
# Binary Functions

In [10]:
np.add(A,B)

array([ 2.28871774,  0.36336366,  2.04172713, -0.06155356,  0.75473994,
        1.94088827,  0.69550653,  1.38397233, -1.59864438,  1.14056552])

In [11]:
np.max(A)

2.159748189067264

In [12]:
np.max(A,B)

TypeError: only integer scalar arrays can be converted to a scalar index

In [13]:
np.maximum(A,B)

array([ 1.64689696,  0.34523529,  1.20792517,  0.95928417,  0.75058787,
        1.49821232,  1.94125291,  2.15974819, -0.43287598,  0.74310244])

In [14]:
np.minimum(A,B)

array([ 0.64182079,  0.01812837,  0.83380196, -1.02083773,  0.00415207,
        0.44267594, -1.24574639, -0.77577586, -1.1657684 ,  0.39746308])

In [16]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True